# Contenido de las páginas de detalle. Marcas: {F-0014 01:08:44} enlaza al minuto,
# {F-0004 p.42} a la página; [[CG]] marca una afirmación que sale de conocimiento
# general y no de una fuente registrada.

DETALLE = {

"plata": dict(
 titulo="¿Nacional pone plata en el proyecto?",
 corto="Las dos partes hablan de los mismos flujos. La discusión real es otra: si esos flujos pueden terminar pagando las pérdidas de los negocios nuevos.",
 posturas=[
  ("Aldabalde", "La caja del club no se toca",
   "“Nacional no interviene un solo dólar, salvo el flujo de los palcos”, que “no está en los flujos recurrentes del club” {F-0016 00:06:59}. La premisa del modelo es que “los flujos actuales del club, con los que el club paga las cuentas, el plantel y todos los gastos, no se tocan” {F-0014 02:28:39}. Lo que va al fideicomiso son los palcos, sus gastos comunes y el Club Social, y según él vuelve “con creces”: 15 M por año después del repago {F-0016 00:29:39}.",
   "Separa la caja operativa (sueldos, plantel, cuentas) de los ingresos que históricamente se destinan a infraestructura. Apela a una lección conocida del club: los fondos del Parque se usaron para otra cosa {F-0014 01:22:08}."),
  ("Decurnex", "Nacional pone 147 M",
   "“Nacional está poniendo 147 millones de dólares”: 93 M de palcos (tres renovaciones en 30 años), 33 M del Club Social y 21 M de gastos comunes. “Se haga el proyecto o no se haga, es plata de Nacional” {F-0015 00:09:37}. Si esa plata respalda negocios que salen mal, “se nos va todo” {F-0015 00:24:36}.",
   "Mira el costo de oportunidad: esos 147 M existen sin el Master Plan y podrían ir solo al estadio. Su propuesta es blindarlos para el Parque y que los negocios los ponga un privado {F-0015 00:23:08}."),
  ("Conductores de Pasión Tricolor", "Son flujos futuros que hoy no entran",
   "“Nacional va a poner flujos que hoy no tiene. Por ejemplo, la renovación de los palcos hoy no los tiene, hoy no está entrando esa plata” {F-0019 00:48:50}. Lo presentan como una respuesta a Decurnex.",
   "Es la misma distinción de Aldabalde: caja actual contra ingresos futuros."),
 ],
 analisis=[
  "**Las dos frases son ciertas, cada una en su marco.** “No se toca la caja” es correcto contablemente: el presupuesto operativo de hoy no financia la obra. “Nacional pone 147 M” es correcto económicamente: son ingresos del club que, sin el proyecto, podrían usarse en otra cosa. Discutir cuál de las dos es la verdadera no lleva a ningún lado.",
  "**La pregunta que importa es otra: ¿esos flujos pueden terminar cubriendo pérdidas de la arena o del estacionamiento?** En un fideicomiso donde todos los ingresos entran a una misma cuenta y pagan una misma deuda, los palcos sostienen todo el conjunto. Si un negocio rinde menos, los palcos pagan la diferencia sin que nadie tome una decisión explícita. Esa es la preocupación de fondo de Decurnex y de Villaverde, y es razonable. [[CG]]",
  "**El borrador de la moción responde justo eso.** Los ingresos existentes de palcos, Club Social o aportes de socios “solo podrán tener como destino el estadio de fútbol […] no pudiendo afectarse a otras unidades de negocio” {F-0009} {F-0014 01:28:06}. Según la lectura que hizo Aldabalde al aire, el borrador también prevé “un mecanismo de compensación o restitución al club de los flujos preexistentes que efectivamente se asignen al proyecto” {F-0014 01:51:29}; el resumen de La Abdón no menciona esa cláusula. Si esa cláusula queda en la moción oficial y el modelo la implementa con cuentas y prelaciones de pago separadas, la objeción principal queda bastante contestada.",
  "**El riesgo está en la implementación.** Separar flujos dentro de un mismo fideicomiso es posible, pero hay que verlo en el contrato y en el modelo: qué deuda paga cada flujo y qué pasa si un negocio no alcanza. Hoy no hay documento que lo muestre. [[CG]]",
 ],
 lectura="Es un falso dilema de comunicación. La pregunta útil es: ¿el modelo definitivo aísla los flujos de palcos y Club Social del riesgo de los negocios nuevos? El borrador dice que sí. Hay que confirmarlo en la moción oficial y en el modelo.",
 resolveria=["Moción oficial: que mantenga la cláusula de destino exclusivo al estadio y el mecanismo de restitución", "Modelo económico: que muestre qué deuda paga cada flujo"],
),

"costo": dict(
 titulo="¿Cuánto cuesta la obra?",
 corto="Con un anteproyecto, cualquier cifra es una estimación con mucha incertidumbre. 112 M y 150 M pueden ser dos puntos de un mismo rango. El problema es comunicar una sola cifra como si fuera cierta.",
 posturas=[
  ("Aldabalde", "112 M con todo actualizado",
   "La cotización original fue de 93 M; CPA la actualizó a “en torno a los 100 millones” (16/07) {F-0018 00:07:58}. El 17/09: “con todas las actualizaciones, todo lo que llaman los soft costs […] está en 112 millones de dólares proyectados en los cuatro o cinco años que va a llevar la obra” {F-0016 00:07:30}. Sumaron honorarios, seguros y costos operativos {F-0014 01:16:25}. El número real “lo vamos a tener en las licitaciones” {F-0016 00:22:22}.",
   "Sostiene que discutir el costo antes del proyecto ejecutivo es discutir en el aire, y que el diseño por etapas permite ajustar, por ejemplo sacando el techo, las cintas digitales y las pantallas, unos 20 M {F-0014 00:53:46}, “el 25 % del costo” {F-0014 01:22:28}."),
  ("Decurnex", "Más de 150 M",
   "Encargó una estimación a RDA, “una de las empresas de ingeniería más importantes del país”: “un costo arriba de los 150 millones” {F-0015 00:08:11}. Según él, el preproyecto no cotiza mobiliario, césped, audio, conectividad ni los anclajes del techo {F-0015 00:07:46}. Pide prever entre 20 y 25% de imprevistos {F-0015 00:36:50}.",
   "Apoya el pedido de proyecto ejecutivo antes de votar en la experiencia del Club Social, que tuvo “entre un 55 y un 60% de sobrecosto” {F-0015 00:20:23}, y en casos de estadios en el exterior."),
  ("Singlet", "Los 105 M dejan rubros afuera",
   "El material entregado a la Directiva parte de 93 M, llega a 105 M con ajuste paramétrico y “no incluye césped, equipamiento deportivo, honorarios de arquitectura e ingeniería, seguros de obra ni costos financieros durante la obra” {F-0017 00:51:51}. Además, en la estimación del estudio, la estructura del techo se cuenta “hasta el cimiento no incluido” {F-0017 01:06:27}.",
   "Trabaja con constructoras viales y dice que las fundaciones pueden pesar mucho según el terreno {F-0017 01:07:28}."),
 ],
 analisis=[
  "**En la etapa de anteproyecto, la incertidumbre de costo es grande por naturaleza.** En la práctica de la ingeniería, las estimaciones conceptuales tienen rangos amplios, que se van cerrando con el proyecto ejecutivo y la licitación. No es raro que la estimación final difiera bastante de la inicial. [[CG]]",
  "**Las dos cifras vienen de partes interesadas.** Los 112 M son del equipo que impulsa el proyecto. Los más de 150 M, de una cotización que encargó el principal opositor. No conocemos el alcance del encargo a RDA ni qué incluyen exactamente los 112 M. Ninguna de las dos es independiente.",
  "**Hay una discrepancia concreta que se puede resolver.** Singlet lee que los 105 M no incluyen honorarios, seguros ni costo financiero. Aldabalde dice que los 112 M sí incluyen honorarios y seguros. Si es así, los 7 M de diferencia parecen poco para cubrir todo eso más césped y equipamiento. Hace falta el desglose.",
  "**Los sobrecostos en estadios son la norma.** En la literatura sobre megaproyectos, los sobrecostos son frecuentes y a menudo grandes, y los estadios no son la excepción. Intervenir un estadio centenario, en uso y con documentación incompleta, suma riesgo. En este punto, la prudencia de Decurnex y Singlet tiene respaldo. [[CG]]",
  "**Aldabalde tiene razón en algo importante:** el costo exacto no se conoce hasta el ejecutivo, y pagar 2 M por un ejecutivo antes de saber si hay respaldo institucional también es un riesgo. Lo que se puede pedir es un rango, con un escenario base y uno pesimista, y saber qué pasa con cada etapa en el pesimista.",
 ],
 lectura="Lo más probable es que la obra completa cueste más de 112 M. Eso no invalida el proyecto, pero cambia la pregunta: ¿aguanta la estructura un sobrecosto de 20, 30 o 40%? Esa respuesta vale más que cualquier cifra puntual.",
 resolveria=["Desglose de los 112 M: qué incluye y qué no", "Informe de RDA: alcance y supuestos", "Un escenario pesimista de costo en el modelo"],
),

"cuota": dict(
 titulo="¿Va a haber una cuota extra? ¿Es obligatoria?",
 corto="El modelo necesita unos 26 M de los socios. Si eso puede ser voluntario y todavía conseguir financiamiento es el punto más débil del planteo oficial.",
 posturas=[
  ("Aldabalde", "Voluntaria, como la del básquetbol",
   "17/09: “Hay cuotas de 40 pesos, de 50 pesos, 100 pesos y que son voluntarias […] ni se habla de 10 dólares” {F-0016 00:09:10}. 25/09: la hipótesis de marzo era que 20.000 socios, un tercio del padrón, pusieran USD 10 por mes durante cinco años; “es una celda de un Excel” y hoy hay otros modelos {F-0014 00:59:56}. Como base cita una encuesta en la que el 78% está dispuesto a colaborar {F-0014 01:00:23} y la cuota del básquetbol, que pagan 32.000 socios {F-0014 01:02:07}. Si no alcanza, los contratos comerciales pueden servir de garantía {F-0014 01:09:14}.",
   "Confía en la respuesta del hincha y en que el proyecto “contagie”. Recuerda que el aumento del 50% de la cuota en 2018 no hizo caer el padrón {F-0014 01:02:21}."),
  ("Decurnex", "Tiene que ser obligatoria",
   "El modelo supone 22.500 socios con USD 10 por mes durante 5 años y 1.000 socios con bonos de USD 2.000 por año {F-0015 00:13:06}. Para quien presta, un supuesto voluntario “es tomado como cero”: “tenés que hacer una suba de cuota inevitable”, cerca de 50% {F-0015 00:14:44}.",
   "Razona como un prestamista: quiere un flujo seguro para ceder en garantía."),
  ("Bardanca y Singlet", "Aporte propio exigido, no voluntario",
   "El financiador exige entre 15 y 20% de aporte propio y no acepta que sea voluntario, porque asume el riesgo de que caigan los socios {F-0017 00:54:19}. Además, el aporte llega año a año y la deuda se desembolsa a la par, así que si la obra se desvía, puede quedar a medias {F-0017 01:01:06}. Singlet: hablar de 40 pesos cuando la cuota voluntaria de básquetbol es de 95 “no es honesto intelectualmente”; si hace falta una sobrecuota de 6 o 7 dólares, “hay que decirlo” {F-0017 00:59:35}.",
   "Lo que piden es transparencia sobre el tamaño real del aporte."),
 ],
 analisis=[
  "**40 o 100 pesos y USD 10 por mes no describen el mismo esquema.** El 17/09 Aldabalde habló de cuotas en pesos, del orden de la del básquetbol, y dijo que “ni se habla de 10 dólares” {F-0016 00:09:42}; el 25/09 reconoció que el modelo de marzo sí suponía USD 10 por mes de 20.000 socios durante cinco años {F-0014 01:00:01}. La escala la dan los propios actores. Singlet: la cuota voluntaria del básquetbol es de 95 pesos, y una sobrecuota que cierre el modelo sería de “seis o siete dólares” {F-0017 00:59:35}. Decurnex: 26 M en cinco años son 5,2 M por año, contra unos 10 M por año que hoy recauda el club de sus socios {F-0015 00:15:06}. Cualquiera sea el tipo de cambio, la cuota que describió el 17/09 y la que estaba en el modelo no son la misma.",
  "**Una encuesta no es un compromiso de pago.** Que el 78% diga que colaboraría no significa que el 78% vaya a pagar todos los meses durante cinco años. La diferencia entre lo que la gente declara y lo que después hace es un fenómeno muy conocido. La cuota del básquetbol es una mejor referencia: 32.000 socios pagan una cuota voluntaria {F-0014 01:02:07}, pero de 95 pesos según Singlet {F-0017 00:59:35}, no de USD 10. [[CG]]",
  "**En financiamiento de proyectos, el aporte propio suele tener que ser firme.** Los prestamistas en general exigen que el promotor aporte una parte con compromiso cierto, y no toman como garantía donaciones voluntarias. En este punto, Decurnex y Bardanca describen bien la práctica habitual. [[CG]]",
  "**Aldabalde tiene un punto válido:** los contratos firmados con terceros solventes, como un alquiler de largo plazo o un contrato de la arena, sí se usan para respaldar financiamiento inmobiliario. Pero eso reemplaza garantías de flujo, no necesariamente el aporte propio. Y hoy esos contratos no existen. [[CG]]",
 ],
 lectura="En este tema, la crítica es más sólida que la defensa. No porque la cuota vaya a ser obligatoria, sino porque el planteo oficial no explica qué pasa si el aporte voluntario no alcanza. La moción debería decirlo expresamente: si hace falta una sobrecuota general, ¿vuelve a la Asamblea?",
 resolveria=["Modelo vigente: cuánto aporte de socios supone y con qué esquema", "Qué pasa si no se llega: alternativa escrita en la moción", "Opinión de CPA o de un financiador sobre si un aporte voluntario sirve"],
),

"570": dict(
 titulo="¿El proyecto genera 570 millones de dólares?",
 corto="Es una suma de 30 años de ingresos. A valor de hoy son unos 103 o 104 M, y en eso las dos partes coinciden. Comparado con un costo de más de 100 M, el proyecto parece más cerca de pagarse solo que de ser un gran negocio.",
 posturas=[
  ("Aldabalde", "570 M en el fideicomiso, 150 M directo al club",
   "“El fideicomiso genera 570 millones de dólares en los 30 años de operación […] y genera a su vez 150 millones de dólares que van directos a Nacional” {F-0016 00:05:03}. Acepta el valor presente: “si esos 570 millones, sacando los palcos, son 82 hoy, los 94 de los palcos son 22” {F-0014 01:44:58}. Pero el flujo se cobra año a año: “queremos que nos pague el alquiler del 47 en el 47” {F-0014 01:46:11}.",
   "Lo que le importa es si el flujo alcanza para pagar la deuda cada año, no el valor presente."),
  ("Bardanca", "A valor presente son 103 M",
   "Sumar todos los años “es un error financiero grave y básico” {F-0017 00:31:00}. “Esos 570 millones son 103 millones de dólares” {F-0017 00:31:30}. Además, los 570 M incluyen palcos, gastos comunes y Club Social, que se cobran igual sin el proyecto {F-0017 00:33:40}. Y los 150 M directos tampoco son 150 a valor presente, e incluyen ahorros que también se lograrían haciendo solo el estadio {F-0017 01:29:15}.",
   "Pide comparar peras con peras: costo de hoy contra ingresos de hoy."),
 ],
 analisis=[
  "**Bardanca tiene razón en lo técnico, y Aldabalde lo acepta.** Un dólar dentro de 25 años vale mucho menos que uno hoy. Comparar 570 M acumulados con un costo de 112 M exagera el atractivo del proyecto. [[CG]]",
  "**Una cuenta gruesa, con las cifras que las dos partes aceptan:** ingresos del fideicomiso a valor presente, unos 103 o 104 M. Costo de obra, unos 112 M repartidos en cuatro o cinco años, que a valor presente es algo menos. El resultado queda cerca del equilibrio. Es una cuenta mía, con supuestos que no conozco (tasa de descuento, si los 570 M son brutos o netos de costos operativos), y puede estar lejos del modelo real.",
  "**Si esa cuenta se acerca a la realidad, el argumento cambia.** El proyecto no sería “un gran negocio que genera 570 M”, sino “un proyecto que se paga más o menos solo y deja un estadio terminado”. Es un argumento legítimo, y quizás más honesto, pero muy sensible a los supuestos: si los ingresos rinden un 20% menos o el costo sube un 20%, el resultado pasa a ser negativo. [[CG]]",
  "**La discusión sobre los palcos importa.** Si 22 de los 104 M a valor presente son palcos, que el club cobraría igual, la parte que genera el proyecto por sí mismo son unos 82 M. Contra un costo de más de 100 M, eso refuerza la pregunta de Bardanca: ¿cuánto aporta cada negocio nuevo?",
 ],
 lectura="La cifra de 570 M no debería usarse para comunicar el proyecto: confunde más de lo que aclara. El dato honesto es el valor presente, y ahí las dos partes coinciden. Con eso, la pregunta pasa a ser si el proyecto se sostiene en un escenario malo, no cuánto gana en el bueno.",
 resolveria=["Modelo: tasa de descuento, ingresos netos y valor presente por unidad de negocio", "Escenarios de sensibilidad: ingresos y costo ±20%"],
),

"parking": dict(
 titulo="¿El estacionamiento da ganancia?",
 corto="Las dos partes leen el mismo modelo y dicen cosas opuestas. Con los números que dio Aldabalde, los ingresos que detalló no llegan ni cerca a los 3 M. Y si el estacionamiento es obligatorio por norma, quizás no hay que evaluarlo como negocio.",
 posturas=[
  ("Aldabalde", "Un negocio de 2 M por año",
   "El 90% del modelo “es la curva de lo que le vamos a cobrar al operador”, no la ocupación {F-0014 01:11:08}. El cálculo es por eventos: 4 shows con ocupación total; 20 partidos a USD 15 descontando los 250 lugares de palquistas, 225.000; copas y clásicos, 75.000; 60 eventos de la arena a USD 10 con 50% de ocupación. En total, “en el mejor escenario, sin IVA, 3 millones de dólares y castigado un 30%, genera 2 millones y medio”, con 500.000 de costo operativo {F-0014 01:12:45} {F-0014 01:13:45}. Además, “no hay estadio sin parking”: la Intendencia lo exige {F-0014 01:10:37}.",
   "Lo ve como parte de un conjunto en el que cada negocio potencia al otro."),
  ("Singlet", "90% de ocupación durante 30 años",
   "“El supuesto del proyecto es que hay una ocupación del 90% durante los 30 años. 882 plazas consecutivas por día durante 30 años ocupadas. Ni en Disney” {F-0017 00:39:24}. Decurnex dijo algo parecido {F-0015 00:18:04}.",
   "Lo lee del material entregado a la Directiva."),
  ("Bardanca", "Valor actual neto negativo",
   "Con el Excel de CPA “evaluación unidad de negocio versión tres”, sin cambiar supuestos, el valor actual neto del estacionamiento da unos −7 M {F-0017 00:43:21}. La arena tampoco genera valor; el zócalo comercial sí {F-0017 00:57:13}.",
   "Evalúa cada negocio por separado: ¿recupera lo que cuesta construirlo?"),
 ],
 analisis=[
  "**Los componentes que detalló Aldabalde no suman 3 M.** Partidos locales, 225.000; copas y clásicos, 75.000; arena, 60 eventos × unos 900 lugares × 50% × USD 10 = unos 270.000. Son unos 570.000. Para llegar a 3 M, los 4 shows tendrían que dejar unos 2,4 M, es decir, más de USD 600 por lugar y por show, algo que no parece plausible. Tiene que haber otros ingresos que no mencionó, como uso diario, mensuales o rotativo en días sin eventos. Si los hay, el “90%” que cita Singlet podría estar justamente ahí. Es una cuenta mía con los datos que él dio al aire.",
  "**Miden cosas distintas.** “2 M por año” es un resultado operativo anual. “−7 M” es el valor actual neto después de restar la inversión. Los dos números pueden ser ciertos a la vez si construir el estacionamiento, en subsuelo y en tres niveles, es muy caro. Los estacionamientos subterráneos son, en general, de las obras más caras por lugar. [[CG]]",
  "**La pregunta que falta: ¿es un negocio o un requisito?** Si la Intendencia exige estacionamiento para habilitar el estadio y la arena, como sugiere Aldabalde, no tiene sentido pedirle que “genere valor” por sí solo: es un costo de hacer el estadio. En ese caso, los dos tendrían parte de razón. Bardanca, en que no es un buen negocio. Aldabalde, en que no se puede prescindir de él. [[CG]]",
  "**La lectura de Aldabalde del 90% es verificable y hay que verla.** Si el documento de marzo dice “ocupación” y el modelo lo usa como tal, Singlet tiene razón en que el supuesto es irreal. Si es un factor sobre el canon del operador, la crítica pierde fuerza.",
 ],
 lectura="Con lo que dijo cada uno, el estacionamiento no se sostiene como negocio independiente; los números que detalló Aldabalde son muy inferiores a los 3 M. Pero probablemente sea un requisito normativo del proyecto. El debate debería pasar de “¿genera valor?” a “¿cuánto hay que construir y cuánto cuesta cumplir la norma?”.",
 resolveria=["Material del 11/03: qué significa exactamente el 90%", "Excel de CPA v3: inversión y flujo del estacionamiento", "Requisito de la Intendencia: cuántos lugares exige"],
),

"solo": dict(
 titulo="¿Se puede terminar solo el estadio?",
 corto="Con las cifras que aceptan las dos partes, los flujos propios del club no alcanzan para un estadio de 80 o 90 M. Una versión reducida, sin techo y con menos etapas, es la alternativa realista, y todavía nadie la terminó de modelar.",
 posturas=[
  ("Aldabalde", "No dan los números",
   "“Para hacer el parque solo no dan los números.” Con los palcos hay 17 M en los próximos 10 años, unos 13 M a valor presente: “con eso el parque no se entera” {F-0016 00:16:13} {F-0016 00:16:20}. El análisis de CPA dice que no es viable {F-0014 02:14:43}. Solo el estadio costaría “80 o 90, capaz 120” {F-0014 01:19:54}.",
   "Es su argumento central: los negocios nuevos son los que pagan el estadio."),
  ("Decurnex", "Estudiar el estadio en exclusividad",
   "Debería haber “un estudio y un análisis pormenorizado y detallado del tema parque en exclusividad” {F-0015 00:16:45}, con los 147 M y el aporte de socios destinados solo al estadio {F-0015 00:23:08}, y los negocios a cargo de un privado {F-0015 00:16:56}.",
   "Prefiere un proyecto más chico con menos riesgo."),
  ("Bardanca", "Estamos trabajando en eso",
   "El Excel de CPA dice que “era complicado hacer solo el estadio” {F-0017 01:20:05}, pero “tenemos indicios de que se podría llegar a estructurar el Parque Central con algunos cambios, por ejemplo, sacándole el techo” {F-0017 01:22:06}. No está terminado.",
   "Reconoce que no es simple y que es un trabajo en curso."),
 ],
 analisis=[
  "**La cuenta gruesa favorece a Aldabalde.** Palcos: unos 22 M a valor presente en 30 años (cifra de Aldabalde). Club Social: unos 33 M nominales en 30 años, bastante menos a valor presente. Aporte de socios: unos 26 M. Aun sumando todo, cuesta llegar a un estadio de 80 o 90 M, más el costo financiero. Es una cuenta mía, gruesa, con cifras de las dos partes, y mezcla bases: los palcos van a valor presente y el Club Social y el aporte de socios, a valor nominal. Esa mezcla infla los recursos disponibles, así que si aun así no alcanza, la conclusión se sostiene.",
  "**Pero el estadio solo también genera ingresos.** Más localidades, hospitalidad, VIP y ahorro de mantenimiento no dependen de la arena ni del zócalo. Bardanca lo señala {F-0017 01:31:44}. En un escenario de solo estadio, esos ingresos también estarían, y achican la brecha.",
  "**Sin techo, el problema cambia de escala.** El techo cuesta unos 20 M según Aldabalde, contando cintas digitales y pantallas {F-0014 00:53:46}, y 21,5 M según Singlet, rubros 12 y 13 del presupuesto {F-0017 01:41:45}. Un estadio sin techo y con etapas priorizadas es un proyecto distinto y más chico. Es razonable pensar que por ahí pase una alternativa viable, pero nadie la presentó con números.",
  "**Hay un problema de tiempos.** A la Asamblea se le pide elegir el camino antes de que exista la comparación con la alternativa. Aldabalde dice que nadie trabajó en un plan B durante un año {F-0014 02:14:43}. Los críticos dicen que recién tuvieron acceso a la información hace unos meses {F-0017 00:11:21}. Las dos cosas pueden ser ciertas.",
 ],
 lectura="Con los números que aceptan las dos partes, un estadio completo solo con recursos propios no cierra. Un estadio reducido quizás sí. La crítica de fondo más fuerte no es que el Master Plan esté mal, sino que se vota sin que exista la alternativa para comparar.",
 resolveria=["Análisis de CPA del escenario de solo estadio", "Alternativa de Singlet y Bardanca terminada y validada por CPA", "Costo del estadio solo, con y sin techo"],
),

"sobrecosto": dict(
 titulo="¿Qué pasa si la obra sale más cara?",
 corto="“No se empieza sin financiamiento” protege contra empezar mal, no contra un sobrecosto en el medio de una etapa. Ahí está el riesgo residual real.",
 posturas=[
  ("Aldabalde", "Lo absorbe el fideicomiso",
   "“El fideicomiso es el responsable de toda la financiación.” Si cuesta 130 en vez de 110, “no vamos a empezar si no tenemos el dinero para financiar esos 130 millones”; en el peor caso, el fideicomiso tarda uno o dos años más en pagar {F-0016 00:24:12} {F-0016 00:24:54}. Cuenta con seguros de construcción, de fiel cumplimiento y de acopios {F-0014 01:17:25}.",
   "Confía en los contratos y seguros bien diseñados, como en su experiencia profesional."),
  ("Decurnex", "El Club Social ya lo mostró",
   "El Club Social “tuvo entre un 55 y un 60% de sobrecosto” {F-0015 00:20:23}; en una obra de esta escala hay que prever entre 20 y 25% de imprevistos {F-0015 00:36:50}.",
   "Habla desde su propia experiencia como presidente."),
  ("Bardanca y Singlet", "No resistimos un desvío del 60%",
   "“Nosotros un desvío de obra del 60% no lo resistimos” {F-0017 01:08:31}. Como el aporte de socios y la deuda entran a la par, “si a mí se me desvió la obra y me consumí el aporte del socio, la obra me queda a la mitad” {F-0017 01:02:06}.",
   "Señalan un riesgo de secuencia, no solo de monto."),
 ],
 analisis=[
  "**La regla “no se empieza sin financiamiento” es buena, pero cubre el comienzo.** Si a mitad de una etapa aparece un sobrecosto (un caño de OSE, una fundación que no estaba prevista), el dinero de esa etapa ya está comprometido. Ahí las opciones son conseguir más financiamiento, recortar alcance o parar. [[CG]]",
  "**Las herramientas habituales existen:** contratos a precio cerrado, garantías de cumplimiento, seguros, fondos de contingencia. El borrador de la moción pide varias: licitación, contratos, garantías, seguros y mecanismos para contingencias antes de cada etapa {F-0009}. Eso reduce el riesgo, pero no lo elimina. Los contratos a precio cerrado suelen costar más, porque el constructor cobra por asumir el riesgo. [[CG]]",
  "**Hay una tensión que conviene mirar.** El borrador dice que el club no aporta capital para sobrecostos. Los prestamistas, en general, piden que alguien responda por los sobrecostos. Si no es el club, van a exigir más contingencia, más tasa o menos alcance. No es un problema insalvable, pero es probable que el financiamiento real sea más caro o más chico que el modelado. [[CG]]",
  "**El diseño en 14 etapas ayuda.** Si cada etapa deja algo que funciona, un sobrecosto frena el avance sin dejar una obra inútil. Parece ser la intención del anteproyecto, que planifica las etapas para “acompasar en forma equilibrada los egresos y la generación de ingresos” {F-0004 p.38}. El riesgo que queda es convivir con un estadio en obra durante años.",
 ],
 lectura="Financieramente, el club está razonablemente protegido si el borrador se mantiene. El riesgo residual es de ejecución y de tiempo: etapas que se atrasan, un Parque en obra más años de lo previsto y un proyecto final más chico que el prometido. Eso también hay que decirlo al votar.",
 resolveria=["Moción oficial: qué pasa si una etapa se queda sin fondos a mitad de camino", "Modelo: contingencia prevista por etapa"],
),

"voto": dict(
 titulo="¿Qué se vota el 24 de octubre y con qué mayoría?",
 corto="Según el borrador, se vota un marco con garantías, no la obra. La mayoría legal parece ser la simple; la política es otra discusión. Llama la atención que el proyecto exija 9 de 11 en la Directiva pero no una mayoría reforzada de los socios.",
 posturas=[
  ("Aldabalde", "Se aprueba un sistema de trabajo",
   "La Asamblea “aprueba el master plan y aprueba un sistema de trabajo que dice que el club no se endeuda, que se dan todas las garantías de que no se inicia si no está el financiamiento” {F-0014 01:56:05}. El 75% salió de una reforma del Estatuto votada “hace dos meses”, que no rige hasta que la apruebe el MEC, y duda de que sea legal fijar una mayoría especial para una sola Asamblea {F-0014 02:16:38}. “A mí me parece perfecto que sea el 75%. Si es lo que el socio levanta la mano en la asamblea” {F-0014 02:20:41}.",
   "Quiere avanzar ahora; ve el 75% como un posible bloqueo hacia adelante."),
  ("Decurnex", "Por coherencia, 75%",
   "El Estatuto vigente dice 50 + 1, pero “si hace dos meses votamos algo, no puede ser que hoy, 60 días después, el proyecto que eventualmente va a ser el más importante de la historia de Nacional…”; lo va a plantear como moción en la Asamblea {F-0015 00:26:52} {F-0015 00:27:13}.",
   "Un proyecto de 30 años aprobado por poco margen divide al club."),
  ("Singlet", "Nos pareció que era tomarnos el pelo",
   "La reforma del 7 de julio fijó el 75% para proyectos de más de USD 2 M. Dos o tres días después, Aldabalde dijo que esta Asamblea se regiría por el Estatuto vigente, con 51%: “a nosotros no nos gustó esa actitud” {F-0017 00:05:19} {F-0017 00:07:23}. Un proyecto de esta envergadura aprobado con 51% “es porque no conoce el club” {F-0017 00:09:40}.",
   "Participó en la redacción de la reforma."),
 ],
 analisis=[
  "**Legalmente, parece mandar el Estatuto vigente.** Si la reforma no está aprobada por el MEC, en principio no rige, y la Asamblea decide por la mayoría que fija el texto vigente. No tenemos el Estatuto ni el trámite, así que esto es una lectura general y no una opinión jurídica. [[CG]]",
  "**Políticamente, Decurnex y Singlet tienen un punto.** Un proyecto de 30 años aprobado 52 a 48 nace débil: cada Directiva futura va a tener la tentación de revisarlo. Aldabalde lo sabe: dice que si se aprueba por poco o no se aprueba, “no pasa nada”, pero también que se necesita el apoyo del socio.",
  "**Hay una asimetría llamativa.** El borrador exige 9 de 11 votos de la Directiva para las decisiones centrales, justamente para asegurar un consenso amplio {F-0009}. Aplicar esa misma lógica a los socios, con una mayoría reforzada, sería coherente. Lo contrario también se puede argumentar: el 75% le da poder de veto a una minoría.",
  "**Lo que se vota es menos de lo que suena, y más de lo que parece.** Según el borrador, no se autorizan obras, deuda ni garantías: cada paso necesita condiciones y, si hay cambios sustanciales, vuelve a la Asamblea. Pero sí se fija el rumbo: se adopta este Master Plan, con estas unidades de negocio, como marco. Una alternativa como el solo estadio pasaría a ser un cambio del marco.",
 ],
 lectura="El 24 de octubre no se vota “hacer o no hacer la obra”, pero sí cuál es el proyecto de referencia. Por eso la mayoría importa. Una salida razonable sería que la propia Asamblea decida primero, como moción de orden, qué mayoría va a exigirse. Así la discusión de la regla no contamina la discusión del proyecto.",
 resolveria=["Texto de la reforma del Estatuto y estado del trámite en el MEC", "Moción oficial", "Opinión jurídica sobre si la Asamblea puede autoimponerse una mayoría especial"],
),
}
