# Contenido de las páginas de detalle. Marcas: {F-0014 01:08:44} enlaza al minuto,
# {F-0004 p.42} a la página; [[CG]] marca una afirmación que sale de conocimiento
# general y no de una fuente registrada.

DETALLE = {

"plata": dict(
 titulo="¿Nacional pone plata en el proyecto?",
 corto="Las dos partes hablan de los mismos flujos, y la moción ya los reserva para el estadio. La discusión que queda es de estructura: si esos flujos van en el mismo fideicomiso que paga la deuda de todo el proyecto o en uno aparte.",
 posturas=[
  ("Aldabalde", "La caja del club no se toca",
   "“Nacional no interviene un solo dólar, salvo el flujo de los palcos”, que “no está en los flujos recurrentes del club” {F-0016 00:06:59}. La premisa del modelo es que “los flujos actuales del club, con los que el club paga las cuentas, el plantel y todos los gastos, no se tocan” {F-0014 02:28:39}. Lo que va al fideicomiso son los palcos, sus gastos comunes y el Club Social, y según él vuelve “con creces”: 15 M por año después del repago {F-0016 00:29:39}.",
   "Separa la caja operativa (sueldos, plantel, cuentas) de los ingresos que históricamente se destinan a infraestructura. Apela a una lección conocida del club: los fondos del Parque se usaron para otra cosa {F-0014 01:22:08}."),
  ("Decurnex", "Nacional pone 147 M; que vayan a un fideicomiso aparte",
   "“Nacional está poniendo 147 millones de dólares”: 93 M de palcos (tres renovaciones en 30 años), 33 M del Club Social y 21 M de gastos comunes. “Se haga el proyecto o no se haga, es plata de Nacional” {F-0015 00:09:37}. Si esa plata respalda negocios que salen mal, “se nos va todo” {F-0015 00:24:36}. El 30/09 fue más allá: esa plata “ya es de Nacional” {F-0022 00:12:32} y tiene que quedar “en un fideicomiso aparte”, solo para el estadio {F-0022 00:06:40}. Si va a un financiamiento global, “después sos rehén de ese financiamiento global, no lo podés sacar, no lo podés rescatar” {F-0022 00:34:25}.",
   "Mira el costo de oportunidad: esos 147 M existen sin el Master Plan y podrían ir solo al estadio. Su propuesta es blindarlos para el Parque y que los negocios los ponga un privado {F-0015 00:23:08}."),
  ("Gomensoro", "Eso ya está en la moción",
   "El destino exclusivo de palcos, gastos comunes, Club Social y aportes extraordinarios al estadio se agregó a la moción “a solicitud de José Decurnex” {F-0021 00:01:04}. Con la moción, “el club no arriesga, el club está blindado” {F-0021 00:08:00}.",
   "Corredactó la moción; presenta la cláusula como una concesión a los críticos. Que la haya pedido Decurnex lo dice solo él."),
  ("Conductores de Pasión Tricolor", "Son flujos futuros que hoy no entran",
   "“Nacional va a poner flujos que hoy no tiene. Por ejemplo, la renovación de los palcos hoy no los tiene, hoy no está entrando esa plata” {F-0019 00:48:50}. Lo presentan como una respuesta a Decurnex.",
   "Es la misma distinción de Aldabalde: caja actual contra ingresos futuros."),
 ],
 analisis=[
  "**Las dos frases son ciertas, cada una en su marco.** “No se toca la caja” es correcto contablemente: el presupuesto operativo de hoy no financia la obra. “Nacional pone 147 M” es correcto económicamente: son ingresos del club que, sin el proyecto, podrían usarse en otra cosa. Discutir cuál de las dos es la verdadera no lleva a ningún lado.",
  "**La pregunta que importa es otra: ¿esos flujos pueden terminar cubriendo pérdidas de la arena o del estacionamiento?** En un fideicomiso donde todos los ingresos entran a una misma cuenta y pagan una misma deuda, los palcos sostienen todo el conjunto. Si un negocio rinde menos, los palcos pagan la diferencia sin que nadie tome una decisión explícita. Esa es la preocupación de fondo de Decurnex y de Villaverde, y es razonable. [[CG]]",
  "**La moción oficial responde justo eso.** Ya la v1 decía que esos ingresos “solo podrán tener como destino el estadio de fútbol GPC y su infraestructura necesaria” {F-0007 p.7}. La v2 va más lejos: los pone en “un fideicomiso independiente, con destino exclusivo al Estadio”, que no puede usarse como garantía de otras unidades {F-0026 p.3}, y excluye las cuotas ordinarias {F-0026 p.4}. También exige “el mecanismo de compensación o restitución al Club de los flujos preexistentes que efectivamente se asignen al proyecto” {F-0026 p.4}.",
  "**El vehículo aparte que pedía Decurnex {F-0022 00:06:40} quedó escrito, con una puerta.** La v2 permite “acuerdos transparentes de servicios, explotación coordinada, distribución de costos comunes” entre vehículos, siempre que no expongan los fondos del estadio a obligaciones ajenas {F-0026 p.3}, y que la infraestructura compartida se pague en la proporción del estadio “mediante un criterio técnico verificable” {F-0026 p.4}. Es razonable, porque estadio, estacionamiento y plaza comparten estructura; pero ese criterio de reparto es donde se juega que la separación sea real. El costo de separar: el resto del proyecto pierde ese respaldo frente a los financiadores. [[CG]]",
 ],
 lectura="Ya no es un falso dilema de comunicación: en el destino y en la estructura hay acuerdo, y la versión 2 de la moción lo escribió: fideicomiso propio para los fondos del estadio {F-0026 p.3}. Lo que queda por ver es el criterio para repartir los costos de la infraestructura compartida, que fija el modelo definitivo.",
 resolveria=["Contrato del fideicomiso del estadio y criterio de reparto de la infraestructura compartida", "Modelo económico: qué deuda paga cada flujo", "Opinión de un financiador: si exige esos flujos como respaldo del conjunto"],
),

"costo": dict(
 titulo="¿Cuánto cuesta la obra?",
 corto="Con un anteproyecto, cualquier cifra es una estimación con mucha incertidumbre. 110 M, 132 M y 170 M pueden ser puntos de un mismo rango. El problema es comunicar una sola cifra como si fuera cierta.",
 posturas=[
  ("Aldabalde", "112 M, después unos 110 M",
   "La cotización original fue de 93 M; CPA la actualizó a “en torno a los 100 millones” (16/07) {F-0018 00:07:58}. El 17/09: “con todas las actualizaciones, todo lo que llaman los soft costs […] está en 112 millones de dólares proyectados en los cuatro o cinco años que va a llevar la obra” {F-0016 00:07:30}. Sumaron honorarios, seguros y costos operativos {F-0014 01:16:25}. El número real “lo vamos a tener en las licitaciones” {F-0016 00:22:22}. El 30/09, en la reunión informativa: “de 93 estamos en 110” {F-0020 00:13:57}, con garantías, seguros y paramétricas de cinco años de obra {F-0020 00:04:16}.",
   "Sostiene que discutir el costo antes del proyecto ejecutivo es discutir en el aire, y que el diseño por etapas permite ajustar, por ejemplo sacando el techo, las cintas digitales y las pantallas, unos 20 M {F-0014 00:53:46}, “el 25 % del costo” {F-0014 01:22:28}."),
  ("Decurnex", "Entre 150 y 170 M",
   "Encargó una estimación a RDA, “una de las empresas de ingeniería más importantes del país”: “un costo arriba de los 150 millones” {F-0015 00:08:11}. Según él, el preproyecto no cotiza mobiliario, césped, audio, conectividad ni los anclajes del techo {F-0015 00:07:46}. Pide prever entre 20 y 25% de imprevistos {F-0015 00:36:50}. El 30/09: “en el eje de los 150, 160 millones” {F-0022 00:05:09}, y una empresa de plaza les dio “una cotización de 170 millones con todos los recados” {F-0022 00:35:55}. Bajó su previsión de imprevistos a “entre un 15, 18%” {F-0022 00:35:25}.",
   "Apoya el pedido de proyecto ejecutivo antes de votar en la experiencia del Club Social, que tuvo “entre un 55 y un 60% de sobrecosto” {F-0015 00:20:23}, y en casos de estadios en el exterior."),
  ("Singlet", "Los 105 M dejan rubros afuera",
   "El material entregado a la Directiva parte de 93 M, llega a 105 M con ajuste paramétrico y “no incluye césped, equipamiento deportivo, honorarios de arquitectura e ingeniería, seguros de obra ni costos financieros durante la obra” {F-0017 00:51:51}. Además, en la estimación del estudio, la estructura del techo se cuenta “hasta el cimiento no incluido” {F-0017 01:06:27}.",
   "Trabaja con constructoras viales y dice que las fundaciones pueden pesar mucho según el terreno {F-0017 01:07:28}."),
  ("Gomensoro", "110 M, con un ajuste de hasta 20%",
   "La primera presentación “llegaba a 110 millones” con honorarios y seguros, y “sobre eso creo que hay que hacer un ajuste de hasta 20%” {F-0021 00:28:11}. El precio real lo da la licitación {F-0021 00:22:19}.",
   "Abogado, no técnico en costos; reconoce el margen de ajuste."),
 ],
 analisis=[
  "**En la etapa de anteproyecto, la incertidumbre de costo es grande por naturaleza.** En la práctica de la ingeniería, las estimaciones conceptuales tienen rangos amplios, que se van cerrando con el proyecto ejecutivo y la licitación. No es raro que la estimación final difiera bastante de la inicial. [[CG]]",
  "**Todas las cifras vienen de partes interesadas.** Los 110 o 112 M son del equipo que impulsa el proyecto, y Gomensoro admite un ajuste de hasta 20%: unos 132 M (cuenta propia). Los 150 a 170 M son de cotizaciones que encargó el principal opositor, y no conocemos ni la empresa ni el alcance. Ninguna es independiente. Lo que llama la atención es que, con el ajuste que reconoce Gomensoro, la distancia entre las dos puntas se achica.",
  "**Hay una discrepancia concreta que se puede resolver.** Singlet lee que los 105 M no incluyen honorarios, seguros ni costo financiero. Aldabalde dice que los 112 M sí incluyen honorarios y seguros. Si es así, los 7 M de diferencia parecen poco para cubrir todo eso más césped y equipamiento. Hace falta el desglose.",
  "**Los sobrecostos en estadios son la norma.** En la literatura sobre megaproyectos, los sobrecostos son frecuentes y a menudo grandes, y los estadios no son la excepción. Intervenir un estadio centenario, en uso y con documentación incompleta, suma riesgo. En este punto, la prudencia de Decurnex y Singlet tiene respaldo. [[CG]]",
  "**Aldabalde tiene razón en algo importante:** el costo exacto no se conoce hasta el ejecutivo, y pagar 2 M por un ejecutivo antes de saber si hay respaldo institucional también es un riesgo. Lo que se puede pedir es un rango, con un escenario base y uno pesimista, y saber qué pasa con cada etapa en el pesimista.",
 ],
 lectura="Lo más probable es que la obra completa cueste más de 110 M; el propio Gomensoro habla de hasta un 20% más. Eso no invalida el proyecto, pero cambia la pregunta: ¿aguanta la estructura un sobrecosto de 20, 30 o 40%? Esa respuesta vale más que cualquier cifra puntual.",
 resolveria=["Desglose de los 110-112 M: qué incluye y qué no", "Cotizaciones de RDA y de la empresa de plaza: alcance y supuestos", "Un escenario pesimista de costo en el modelo"],
),

"cuota": dict(
 titulo="¿Va a haber una cuota extra? ¿Es obligatoria?",
 corto="El modelo necesita unos 26 M de los socios. Si eso puede ser voluntario y todavía conseguir financiamiento es el punto más débil del planteo oficial.",
 posturas=[
  ("Aldabalde", "Voluntaria, como la del básquetbol",
   "17/09: “Hay cuotas de 40 pesos, de 50 pesos, 100 pesos y que son voluntarias […] ni se habla de 10 dólares” {F-0016 00:09:10}. 25/09: la hipótesis de marzo era que 20.000 socios, un tercio del padrón, pusieran USD 10 por mes durante cinco años; “es una celda de un Excel” y hoy hay otros modelos {F-0014 00:59:56}. Como base cita una encuesta en la que el 78% está dispuesto a colaborar {F-0014 01:00:23} y la cuota del básquetbol, que pagan 32.000 socios {F-0014 01:02:07}. Si no alcanza, los contratos comerciales pueden servir de garantía {F-0014 01:09:14}. El 30/09: los aportes son “siempre voluntarios”; uno de los modelos es que un tercio de los socios ponga USD 10 por mes durante la obra {F-0020 00:06:24}.",
   "Confía en la respuesta del hincha y en que el proyecto “contagie”. Recuerda que el aumento del 50% de la cuota en 2018 no hizo caer el padrón {F-0014 01:02:21}."),
  ("Gomensoro", "Voluntaria, pero con permanencia por defecto",
   "“Siempre va a ser voluntaria”, con el esquema del básquetbol: “por defecto quedás adentro, pero te podés bajar”, por ejemplo durante cinco años; el que no llega a fin de mes “tiene la posibilidad de bajarse” {F-0021 00:20:03}.",
   "Busca un aporte que se parezca a una cuota firme sin obligar a nadie."),
  ("Decurnex", "Tiene que ser obligatoria",
   "El modelo supone 22.500 socios con USD 10 por mes durante 5 años y 1.000 socios con bonos de USD 2.000 por año {F-0015 00:13:06}. Para quien presta, un supuesto voluntario “es tomado como cero”: “tenés que hacer una suba de cuota inevitable”, cerca de 50% {F-0015 00:14:44}. El 30/09: el aporte de 26 M “se dice que es voluntario, que no es voluntario”: ante un financiador “no hay otra que sea a través de una suba de cuota” {F-0022 00:04:09}. Suma unos 8,5 M pensados de exjugadores y glorias {F-0022 00:04:39}.",
   "Razona como un prestamista: quiere un flujo seguro para ceder en garantía."),
  ("Bardanca y Singlet", "Aporte propio exigido, no voluntario",
   "El financiador exige entre 15 y 20% de aporte propio y no acepta que sea voluntario, porque asume el riesgo de que caigan los socios {F-0017 00:54:19}. Además, el aporte llega año a año y la deuda se desembolsa a la par, así que si la obra se desvía, puede quedar a medias {F-0017 01:01:06}. Singlet: hablar de 40 pesos cuando la cuota voluntaria de básquetbol es de 95 “no es honesto intelectualmente”; si hace falta una sobrecuota de 6 o 7 dólares, “hay que decirlo” {F-0017 00:59:35}.",
   "Lo que piden es transparencia sobre el tamaño real del aporte."),
 ],
 analisis=[
  "**40 o 100 pesos y USD 10 por mes no describen el mismo esquema.** El 17/09 Aldabalde habló de cuotas en pesos, del orden de la del básquetbol, y dijo que “ni se habla de 10 dólares” {F-0016 00:09:42}; el 25/09 reconoció que el modelo de marzo sí suponía USD 10 por mes de 20.000 socios durante cinco años {F-0014 01:00:01}. La escala la dan los propios actores. Singlet: la cuota voluntaria del básquetbol es de 95 pesos, y una sobrecuota que cierre el modelo sería de “seis o siete dólares” {F-0017 00:59:35}. Decurnex: 26 M en cinco años son 5,2 M por año, contra unos 10 M por año que hoy recauda el club de sus socios {F-0015 00:15:06}. Cualquiera sea el tipo de cambio, la cuota que describió el 17/09 y la que estaba en el modelo no son la misma.",
  "**“Voluntaria con permanencia por defecto” es un diseño distinto, y probablemente más eficaz.** Lo que se elige por defecto suele pesar mucho en lo que la gente termina haciendo: con permanencia automática, la adhesión es bastante mayor que cuando hay que anotarse [[CG]]. Eso acerca el aporte a lo que pide un financiador, pero cambia el mensaje: no es lo mismo “podés colaborar” que “vas a pagar salvo que pidas la baja”. Es la descripción de Gomensoro; la moción habla de “aportes extraordinarios de socios destinados específicamente a estas obras” y no define el mecanismo {F-0026 p.4}.",
  "**Una encuesta no es un compromiso de pago.** Que el 78% diga que colaboraría no significa que el 78% vaya a pagar todos los meses durante cinco años. La diferencia entre lo que la gente declara y lo que después hace es un fenómeno muy conocido. La cuota del básquetbol es una mejor referencia: 32.000 socios pagan una cuota voluntaria {F-0014 01:02:07}, pero de 95 pesos según Singlet {F-0017 00:59:35}, no de USD 10. [[CG]]",
  "**En financiamiento de proyectos, el aporte propio suele tener que ser firme.** Los prestamistas en general exigen que el promotor aporte una parte con compromiso cierto, y no toman como garantía donaciones voluntarias. En este punto, Decurnex y Bardanca describen bien la práctica habitual. [[CG]]",
  "**Aldabalde tiene un punto válido:** los contratos firmados con terceros solventes, como un alquiler de largo plazo o un contrato de la arena, sí se usan para respaldar financiamiento inmobiliario. Pero eso reemplaza garantías de flujo, no necesariamente el aporte propio. Y hoy esos contratos no existen. [[CG]]",
 ],
 lectura="En este tema, la crítica es más sólida que la defensa. No porque la cuota vaya a ser obligatoria, sino porque el planteo oficial no explica qué pasa si el aporte voluntario no alcanza, y ahora aparece un tercer diseño, con permanencia por defecto, que no está escrito en ningún lado. La moción no lo dice: si hace falta una sobrecuota general o con baja voluntaria, ¿quién la aprueba?",
 resolveria=["Modelo vigente: cuánto aporte de socios supone y con qué esquema", "Reglamentación: si la sobrecuota es de adhesión o con baja voluntaria, y quién la aprueba", "Opinión de CPA o de un financiador sobre si un aporte voluntario sirve"],
),

"570": dict(
 titulo="¿El proyecto genera 570 millones de dólares?",
 corto="Es una suma de 30 años de ingresos. A valor de hoy son unos 103 o 104 M, y en eso las dos partes coinciden. Comparado con un costo de más de 100 M, el proyecto parece más cerca de pagarse solo que de ser un gran negocio.",
 posturas=[
  ("Aldabalde", "570 M en el fideicomiso, 150 M directo al club",
   "“El fideicomiso genera 570 millones de dólares en los 30 años de operación […] y genera a su vez 150 millones de dólares que van directos a Nacional” {F-0016 00:05:03}. Acepta el valor presente: “si esos 570 millones, sacando los palcos, son 82 hoy, los 94 de los palcos son 22” {F-0014 01:44:58}. Pero el flujo se cobra año a año: “queremos que nos pague el alquiler del 47 en el 47” {F-0014 01:46:11}. El 30/09 sumó unos 5 M por año que irían directo al club, fuera del fideicomiso, desde que opera el estadio, 4 M si se castiga {F-0020 00:26:42} {F-0020 00:37:13}.",
   "Lo que le importa es si el flujo alcanza para pagar la deuda cada año, no el valor presente."),
  ("Bardanca", "A valor presente son 103 M",
   "Sumar todos los años “es un error financiero grave y básico” {F-0017 00:31:00}. “Esos 570 millones son 103 millones de dólares” {F-0017 00:31:30}. Además, los 570 M incluyen palcos, gastos comunes y Club Social, que se cobran igual sin el proyecto {F-0017 00:33:40}. Y los 150 M directos tampoco son 150 a valor presente, e incluyen ahorros que también se lograrían haciendo solo el estadio {F-0017 01:29:15}.",
   "Pide comparar peras con peras: costo de hoy contra ingresos de hoy."),
  ("Decurnex", "Hay que traerlo a valor presente",
   "“El dólar dentro de 30 años no tiene nada que ver con el dólar de hoy” {F-0022 00:12:02}. Y de esos flujos, unos 147 M “ya son de Nacional”: “no se necesita hacer nada para que ese flujo entre” {F-0022 00:12:32}.",
   "Coincide con Bardanca en el método."),
 ],
 analisis=[
  "**Bardanca tiene razón en lo técnico, y Aldabalde lo acepta.** Un dólar dentro de 25 años vale mucho menos que uno hoy. Comparar 570 M acumulados con un costo de 112 M exagera el atractivo del proyecto. [[CG]]",
  "**Una cuenta gruesa, con las cifras que las dos partes aceptan:** ingresos del fideicomiso a valor presente, unos 103 o 104 M. Costo de obra, unos 112 M repartidos en cuatro o cinco años, que a valor presente es algo menos. El resultado queda cerca del equilibrio. Es una cuenta mía, con supuestos que no conozco (tasa de descuento, si los 570 M son brutos o netos de costos operativos), y puede estar lejos del modelo real.",
  "**Si esa cuenta se acerca a la realidad, el argumento cambia.** El proyecto no sería “un gran negocio que genera 570 M”, sino “un proyecto que se paga más o menos solo y deja un estadio terminado”. Es un argumento legítimo, y quizás más honesto, pero muy sensible a los supuestos: si los ingresos rinden un 20% menos o el costo sube un 20%, el resultado pasa a ser negativo. [[CG]]",
  "**La discusión sobre los palcos importa.** Si 22 de los 104 M a valor presente son palcos, que el club cobraría igual, la parte que genera el proyecto por sí mismo son unos 82 M. Contra un costo de más de 100 M, eso refuerza la pregunta de Bardanca: ¿cuánto aporta cada negocio nuevo?",
  "**Los 5 M por año fuera del fideicomiso merecen el mismo examen.** Incluyen 500.000 por año de 10.000 lugares más en cinco partidos {F-0020 00:28:00} y ahorros de operación. Pero en la misma reunión Aldabalde dijo que el modelo supone que el club no vende “una entrada más” {F-0020 00:50:28}. Puede ser que hable de dos cuentas distintas, la del fideicomiso y la del club; hay que verlo en el modelo. Además, parte de ese ahorro también existiría con solo el estadio, como señala Bardanca {F-0017 01:29:15}.",
 ],
 lectura="La cifra de 570 M no debería usarse para comunicar el proyecto: confunde más de lo que aclara. El dato honesto es el valor presente, y ahí las dos partes coinciden. Con eso, la pregunta pasa a ser si el proyecto se sostiene en un escenario malo, no cuánto gana en el bueno.",
 resolveria=["Modelo: tasa de descuento, ingresos netos y valor presente por unidad de negocio", "Escenarios de sensibilidad: ingresos y costo ±20%"],
),

"parking": dict(
 titulo="¿El estacionamiento da ganancia?",
 corto="Las dos partes leen el mismo modelo y dicen cosas opuestas. Con los números que dio Aldabalde, los ingresos que detalló no llegan ni cerca a los 3 M. Y si el estacionamiento es obligatorio por norma, quizás no hay que evaluarlo como negocio.",
 posturas=[
  ("Aldabalde", "Un negocio de 2 M por año",
   "El 90% del modelo “es la curva de lo que le vamos a cobrar al operador”, no la ocupación {F-0014 01:11:08}. El cálculo es por eventos: 4 shows con ocupación total; 20 partidos a USD 15 descontando los 250 lugares de palquistas, 225.000; copas y clásicos, 75.000; 60 eventos de la arena a USD 10 con 50% de ocupación. En total, “en el mejor escenario, sin IVA, 3 millones de dólares y castigado un 30%, genera 2 millones y medio”, con 500.000 de costo operativo {F-0014 01:12:45} {F-0014 01:13:45}. Además, “no hay estadio sin parking”: la Intendencia lo exige {F-0014 01:10:37}. El 30/09: cuando CPA analiza las unidades una por una, “la que menos rentable [...] sigue siendo rentable” {F-0020 00:30:55}; en el análisis por unidad “hubo un error en la asignación de los fondos que significaban inversión con los flujos que generaban esas unidades” {F-0020 00:31:08}. Y es obligatorio: “mal obligación municipal” {F-0020 00:31:23}.",
   "Lo ve como parte de un conjunto en el que cada negocio potencia al otro."),
  ("Singlet", "90% de ocupación durante 30 años",
   "“El supuesto del proyecto es que hay una ocupación del 90% durante los 30 años. 882 plazas consecutivas por día durante 30 años ocupadas. Ni en Disney” {F-0017 00:39:24}. Decurnex dijo algo parecido {F-0015 00:18:04}. Decurnex lo repitió el 30/09: “880 estacionamientos ocupados durante 30 años” {F-0022 00:05:39}.",
   "Lo lee del material entregado a la Directiva."),
  ("Bardanca", "Valor actual neto negativo",
   "Con el Excel de CPA “evaluación unidad de negocio versión tres”, sin cambiar supuestos, el valor actual neto del estacionamiento da unos −7 M {F-0017 00:43:21}. La arena tampoco genera valor; el zócalo comercial sí {F-0017 00:57:13}.",
   "Evalúa cada negocio por separado: ¿recupera lo que cuesta construirlo?"),
 ],
 analisis=[
  "**Los componentes que detalló Aldabalde no suman 3 M.** Partidos locales, 225.000; copas y clásicos, 75.000; arena, 60 eventos × unos 900 lugares × 50% × USD 10 = unos 270.000. Son unos 570.000. Para llegar a 3 M, los 4 shows tendrían que dejar unos 2,4 M, es decir, más de USD 600 por lugar y por show, algo que no parece plausible. Tiene que haber otros ingresos que no mencionó, como uso diario, mensuales o rotativo en días sin eventos. Si los hay, el “90%” que cita Singlet podría estar justamente ahí. Es una cuenta mía con los datos que él dio al aire.",
  "**El “error en la asignación” puede ser la clave, y hay que verlo.** Si el análisis por unidad que usó Bardanca cargaba al estacionamiento inversión que no le correspondía, el −7 M cambia. Si no, el error estaría del otro lado. Aldabalde no dijo quién lo cometió ni en qué documento {F-0020 00:31:08}, y el Excel corregido no está publicado.",
  "**Miden cosas distintas.** “2 M por año” es un resultado operativo anual. “−7 M” es el valor actual neto después de restar la inversión. Los dos números pueden ser ciertos a la vez si construir el estacionamiento, en subsuelo y en tres niveles, es muy caro. Los estacionamientos subterráneos son, en general, de las obras más caras por lugar. [[CG]]",
  "**La pregunta que falta: ¿es un negocio o un requisito?** Si la Intendencia exige estacionamiento para habilitar el estadio y la arena, como sugiere Aldabalde, no tiene sentido pedirle que “genere valor” por sí solo: es un costo de hacer el estadio. En ese caso, los dos tendrían parte de razón. Bardanca, en que no es un buen negocio. Aldabalde, en que no se puede prescindir de él. [[CG]]",
  "**La lectura de Aldabalde del 90% es verificable y hay que verla.** Si el documento de marzo dice “ocupación” y el modelo lo usa como tal, Singlet tiene razón en que el supuesto es irreal. Si es un factor sobre el canon del operador, la crítica pierde fuerza.",
 ],
 lectura="Con lo que dijo cada uno, el estacionamiento no se sostiene como negocio independiente; los números que detalló Aldabalde son muy inferiores a los 3 M. Pero probablemente sea un requisito normativo del proyecto. El debate debería pasar de “¿genera valor?” a “¿cuánto hay que construir y cuánto cuesta cumplir la norma?”.",
 resolveria=["Excel de CPA v3 y su versión corregida: inversión y flujo del estacionamiento", "Material del 11/03: qué significa exactamente el 90%", "Requisito de la Intendencia: cuántos lugares exige"],
),

"solo": dict(
 titulo="¿Se puede terminar solo el estadio?",
 corto="Con las cifras que aceptan las dos partes, los flujos propios del club no alcanzan para un estadio completo de 80 o 90 M. Una versión reducida, sin techo y con menos etapas, es la alternativa realista: según los técnicos de Decurnex sí alcanza, pero su evaluación no está publicada.",
 posturas=[
  ("Aldabalde", "No dan los números",
   "“Para hacer el parque solo no dan los números.” Con los palcos hay 17 M en los próximos 10 años, unos 13 M a valor presente: “con eso el parque no se entera” {F-0016 00:16:13} {F-0016 00:16:20}. El análisis de CPA dice que no es viable {F-0014 02:14:43}. Solo el estadio costaría “80 o 90, capaz 120” {F-0014 01:19:54}. El 30/09: “el parque solo no se puede hacer; se puede hacer [...] un parche” {F-0020 00:42:23}, o un proyecto de a pedacitos que “va a llevar 10, 15, 20 años” {F-0020 00:43:04}.",
   "Es su argumento central: los negocios nuevos son los que pagan el estadio."),
  ("Decurnex", "Con los flujos propios se puede, sin techo",
   "Debería haber “un estudio y un análisis pormenorizado y detallado del tema parque en exclusividad” {F-0015 00:16:45}, con los 147 M y el aporte de socios destinados solo al estadio {F-0015 00:23:08}, y los negocios a cargo de un privado {F-0015 00:16:56}. El 30/09: un grupo de técnicos evaluó si el parque se puede terminar con esos flujos: “la respuesta es que sí. Capaz que sin techo, seguramente sin techo” {F-0022 00:12:32} {F-0022 00:13:02}.",
   "Prefiere un proyecto más chico con menos riesgo."),
  ("Bardanca", "Estamos trabajando en eso",
   "El Excel de CPA dice que “era complicado hacer solo el estadio” {F-0017 01:20:05}, pero “tenemos indicios de que se podría llegar a estructurar el Parque Central con algunos cambios, por ejemplo, sacándole el techo” {F-0017 01:22:06}. No está terminado.",
   "Reconoce que no es simple y que es un trabajo en curso."),
  ("Gomensoro", "Si no sale la moción, abierto a otro proyecto",
   "Si no se aprueba la moción principal, estaría dispuesto a considerar otro proyecto para el estadio, “porque yo quiero que haya obras y no necesariamente que incluyan todo” {F-0021 00:17:48}.",
   "Defiende la moción, pero no descarta un plan más chico."),
 ],
 analisis=[
  "**La cuenta gruesa favorece a Aldabalde.** Palcos: unos 22 M a valor presente en 30 años (cifra de Aldabalde). Club Social: unos 33 M nominales en 30 años, bastante menos a valor presente. Aporte de socios: unos 26 M. Aun sumando todo, cuesta llegar a un estadio de 80 o 90 M, más el costo financiero. Es una cuenta mía, gruesa, con cifras de las dos partes, y mezcla bases: los palcos van a valor presente y el Club Social y el aporte de socios, a valor nominal. Esa mezcla infla los recursos disponibles, así que si aun así no alcanza, la conclusión se sostiene.",
  "**Pero el estadio solo también genera ingresos.** Más localidades, hospitalidad, VIP y ahorro de mantenimiento no dependen de la arena ni del zócalo. Bardanca lo señala {F-0017 01:31:44}. En un escenario de solo estadio, esos ingresos también estarían, y achican la brecha.",
  "**Sin techo, el problema cambia de escala.** El techo cuesta unos 20 M según Aldabalde, contando cintas digitales y pantallas {F-0014 00:53:46}, y 21,5 M según Singlet, rubros 12 y 13 del presupuesto {F-0017 01:41:45}. Un estadio sin techo y con etapas priorizadas es un proyecto distinto y más chico. Es razonable pensar que por ahí pase una alternativa viable, pero nadie la presentó con números.",
  "**Hay un problema de tiempos, y ahora hay una propuesta para resolverlo.** A la Asamblea se le pide elegir el camino antes de que exista la comparación con la alternativa. La moción de la agrupación Atilio García propone justamente eso: un proyecto ejecutivo con el estadio analizado por separado y el techo aparte, y volver a votar después {F-0023}. El costo es tiempo y unos 2 M sin inversor asegurado, que es lo que objeta Gomensoro {F-0021 00:13:37}. Es un desacuerdo de valores sobre cuánto saber antes de decidir.",
 ],
 lectura="Con los números que aceptan las dos partes, un estadio completo solo con recursos propios no cierra. Un estadio reducido, sin techo, quizás sí: los técnicos de Decurnex dicen que sí, pero su evaluación no está publicada. La crítica de fondo más fuerte no es que el Master Plan esté mal, sino que se vota sin que exista la alternativa para comparar.",
 resolveria=["Análisis de CPA del escenario de solo estadio", "Evaluación de los técnicos de Decurnex, publicada y validada por CPA", "Costo del estadio solo, con y sin techo"],
),

"orden": dict(
 titulo="¿Qué se hace primero?",
 corto="El anteproyecto empieza por el estacionamiento y el zócalo comercial; las primeras mejoras del estadio son los accesos de la etapa 2, las de cancha y tribunas empiezan en la 3, y el techo va casi al final. La moción pide priorizar el estadio, pero no fija un orden, y las dos partes dicen querer lo mismo.",
 posturas=[
  ("Gomensoro", "La numeración no es un orden",
   "Que primero van el estacionamiento o el zócalo es “una gran falacia”: el estudio “ordenó en 14 etapas y puso 1 o 2, pero no a título de secuencial” {F-0021 00:18:00} {F-0021 00:18:16}. Lo que vale es la moción: “deberá priorizarse el inicio de aquellas etapas que involucren directamente al Estadio” {F-0021 00:19:17}. Si un inversor viene primero por la arena, “no vamos a frenar” {F-0021 00:18:46}.",
   "Defiende que la moción ya resuelve la prioridad."),
  ("Decurnex", "Partir por unidad de negocio, empezando por el estadio",
   "“Yo creo que sí se puede” cambiar el orden {F-0022 00:22:30}. Hoy el estadio “empieza en la fase tres, fase cuatro” {F-0022 00:23:00}. Propone ordenar por unidades de negocio, con el costo y el ingreso de cada una, “no por fases arquitectónicas”, y arrancar por el estadio {F-0022 00:36:28}. Si no, “en el momento X no te va bien, te quedaste sin el parque” {F-0022 00:24:00}.",
   "Teme que el estadio quede atado al éxito de los otros negocios."),
  ("Aldabalde", "Todo junto, con prioridad del estadio",
   "Si se consigue todo el financiamiento, “tratemos de hacer todo juntos, con la prioridad del estadio” {F-0020 00:33:22}. Si no alcanza, una opción es postergar el techo {F-0020 00:08:26}.",
   "Lo ve como un proyecto integral."),
 ],
 analisis=[
  "**El anteproyecto sí presenta un orden, y lo justifica.** Habla de una “planificación de etapas” ordenada para “acompasar en forma equilibrada los egresos y la generación de ingresos de cada etapa” {F-0004 p.38}: empezar por lo que genera ingresos. Decir que la numeración es solo una lista, como dice Gomensoro, no es lo que se lee en el documento. Pero es un documento de junio de 2025, y la moción, de 15 meses después, pone como primera etapa el proyecto ejecutivo del estadio y prioriza sus etapas {F-0026 p.2}. Además, el estadio no espera hasta la etapa 3, como dijo Decurnex {F-0022 00:23:00}: la etapa 2 ya mejora los accesos a la Atilio García y la Abdón Porte {F-0004 p.38}.",
  "**Empezar por el estacionamiento tiene lógica de obra.** La etapa 1 incluye mudar el estacionamiento existente y reubicar las canchas de tenis {F-0004 p.38}, algo que suele hacerse primero para liberar espacio. Que vaya primero no significa necesariamente que se priorice el negocio. [[CG]]",
  "**La diferencia de fondo no es el orden, sino el amarre.** Las dos partes dicen que el estadio va primero. Decurnex quiere además que el estadio no dependa del resultado de los otros negocios; la versión 2 de la moción lo prioriza y pone sus fondos en un fideicomiso propio {F-0026 p.3}, aunque permite obras habilitantes o unidades complementarias si se justifican {F-0026 p.2}. Ver [[>detalle-plata.html|la plata del club]].",
 ],
 lectura="Hoy no hay un orden definitivo: el del anteproyecto prioriza los ingresos y la moción pide priorizar el estadio sin decir cómo. Antes de votar vale preguntar qué etapas del estadio vienen primero y si dependen de que se financien las demás.",
 resolveria=["Plan de etapas actualizado que respete la prioridad de la moción", "Qué etapas del estadio pueden hacerse sin depender de otras unidades", "Costo e ingreso por unidad de negocio, como pide Decurnex"],
),

"sobrecosto": dict(
 titulo="¿Qué pasa si la obra sale más cara?",
 corto="“No se empieza sin financiamiento” protege contra empezar mal, no contra un sobrecosto en el medio de una etapa. Ahí está el riesgo residual real.",
 posturas=[
  ("Aldabalde", "Lo absorbe el fideicomiso",
   "“El fideicomiso es el responsable de toda la financiación.” Si cuesta 130 en vez de 110, “no vamos a empezar si no tenemos el dinero para financiar esos 130 millones”; en el peor caso, el fideicomiso tarda uno o dos años más en pagar {F-0016 00:24:12} {F-0016 00:24:54}. Cuenta con seguros de construcción, de fiel cumplimiento y de acopios {F-0014 01:17:25}. El 30/09: si caen los ingresos, “vamos a tener que pagar un año más o dos años más” {F-0020 00:38:33}; el primer modelo se repagaba en 10 años y, con menos presión, “podemos terminar de pagar en 15 años” {F-0020 00:36:44}.",
   "Confía en los contratos y seguros bien diseñados, como en su experiencia profesional."),
  ("Decurnex", "El Club Social ya lo mostró",
   "El Club Social “tuvo entre un 55 y un 60% de sobrecosto” {F-0015 00:20:23}; en una obra de esta escala hay que prever entre 20 y 25% de imprevistos {F-0015 00:36:50}. El 30/09: si le va peor al proyecto, “tenés que extender el tiempo de repago, es la única alternativa”, con un repago “más cerca de los 15” años {F-0022 00:29:46}. El Club Social se planteó en 4 M y terminó en unos 6,5 M {F-0022 00:31:17}. Y bajó su previsión de imprevistos a 15-18% {F-0022 00:35:25}.",
   "Habla desde su propia experiencia como presidente."),
  ("Bardanca y Singlet", "No resistimos un desvío del 60%",
   "“Nosotros un desvío de obra del 60% no lo resistimos” {F-0017 01:08:31}. Como el aporte de socios y la deuda entran a la par, “si a mí se me desvió la obra y me consumí el aporte del socio, la obra me queda a la mitad” {F-0017 01:02:06}.",
   "Señalan un riesgo de secuencia, no solo de monto."),
  ("Gomensoro", "Más tiempo de fideicomiso, como el Club Social",
   "“Estaremos más tiempo en la duración del fideicomiso” {F-0021 00:12:01}. El Club Social “se iba a pagar en cuatro años y van ocho”, pero el club no tuvo que poner plata {F-0021 00:29:25}.",
   "Usa el Club Social como ejemplo de que el esquema protege al club."),
 ],
 analisis=[
  "**En qué pasa si sale más caro, las dos partes ahora dicen lo mismo:** se estira el repago, a unos 15 años {F-0020 00:36:44} {F-0022 00:29:46}. Lo que discuten es qué arriesga el club mientras tanto. Para el oficialismo, nada, porque solo pagan la deuda los flujos del fideicomiso. Para Decurnex, los flujos propios del club quedan atados más tiempo a esa deuda {F-0022 00:34:25}.",
  "**La regla “no se empieza sin financiamiento” es buena, pero cubre el comienzo.** Si a mitad de una etapa aparece un sobrecosto (un caño de OSE, una fundación que no estaba prevista), el dinero de esa etapa ya está comprometido. Ahí las opciones son conseguir más financiamiento, recortar alcance o parar. [[CG]]",
  "**Las herramientas habituales existen:** contratos a precio cerrado, garantías de cumplimiento, seguros, fondos de contingencia. La moción pide varias antes de cada etapa: licitación, contratos, garantías de cumplimiento, seguros y mecanismos de cobertura de contingencias {F-0026 p.5}. Eso reduce el riesgo, pero no lo elimina. Los contratos a precio cerrado suelen costar más, porque el constructor cobra por asumir el riesgo. [[CG]]",
  "**Hay una tensión que conviene mirar.** La moción dice que el club no asume “obligaciones de aporte de capital para cobertura de sobrecostos o déficits operativos” {F-0026 p.4}. Los prestamistas, en general, piden que alguien responda por los sobrecostos. Si no es el club, van a exigir más contingencia, más tasa o menos alcance. No es un problema insalvable, pero es probable que el financiamiento real sea más caro o más chico que el modelado. [[CG]]",
  "**El diseño en 14 etapas ayuda.** Si cada etapa deja algo que funciona, un sobrecosto frena el avance sin dejar una obra inútil. Parece ser la intención del anteproyecto, que planifica las etapas para “acompasar en forma equilibrada los egresos y la generación de ingresos” {F-0004 p.38}. El riesgo que queda es convivir con un estadio en obra durante años.",
  "**El fideicomiso tiene un límite de tiempo.** Según Aldabalde, en Uruguay dura 30 años y después se extingue {F-0020 00:34:09}. Con un repago de 15 años hay margen, pero nadie explicó qué pasa si a los 30 años todavía queda deuda. Es una pregunta para el contrato. [[CG]]",
 ],
 lectura="Financieramente, el club está razonablemente protegido si la moción se cumple. El riesgo residual es de ejecución y de tiempo: etapas que se atrasan, un Parque en obra más años de lo previsto y un proyecto final más chico que el prometido. Eso también hay que decirlo al votar.",
 resolveria=["Reglamentación o contrato de fideicomiso: qué pasa si una etapa se queda sin fondos a mitad de camino (la moción no lo dice)", "Modelo: contingencia prevista por etapa y escenario de repago a 15 años", "Contrato: qué pasa con la deuda que quede al extinguirse el fideicomiso"],
),

"voto": dict(
 titulo="¿Qué se vota el 24 de octubre y con qué mayoría?",
 corto="Según la moción oficial, se vota un marco con garantías, no la obra. La mayoría legal parece ser la simple; la política es otra discusión. Llama la atención que la moción exija unanimidad en la Directiva pero no una mayoría reforzada de los socios.",
 posturas=[
  ("Gomensoro", "Rige el 50% más uno",
   "Fue el miembro informante de la reforma. Mientras no la apruebe el MEC y se publique, rige el Estatuto vigente: una moción que pida el 75% “no tiene valor alguno” {F-0021 00:59:59}, y ve “muy difícil” que esté vigente el sábado 24 {F-0021 01:00:48}. La reforma la propuso la CPO para que el proyecto aprobado no se cambie con liviandad {F-0021 00:56:08}. Si hay dos mociones contradictorias, se votan en orden y, si sale la primera, la otra no se vota {F-0021 00:15:13}. Sobre los críticos: “el único propósito de hablar del 75% es tratar de no llegar a los votos” {F-0021 01:03:36}.",
   "Es abogado y parte: corredactó la moción y la reforma."),
  ("Aldabalde", "Se aprueba un sistema de trabajo",
   "La Asamblea “aprueba el master plan y aprueba un sistema de trabajo que dice que el club no se endeuda, que se dan todas las garantías de que no se inicia si no está el financiamiento” {F-0014 01:56:05}. El 75% salió de una reforma del Estatuto votada “hace dos meses”, que no rige hasta que la apruebe el MEC, y duda de que sea legal fijar una mayoría especial para una sola Asamblea {F-0014 02:16:38}. “A mí me parece perfecto que sea el 75%. Si es lo que el socio levanta la mano en la asamblea” {F-0014 02:20:41}. El 30/09, en la reunión informativa, la reforma exige 75% para proyectos de más de 2,5 M {F-0020 00:17:00}; como opinión personal, “capaz que hay que hacer otra asamblea cuando realmente se apruebe la ejecución de las obras” por el 75%, si ya rige, y aclaró que eso lo tienen que responder los abogados {F-0020 00:18:19}.",
   "Quiere avanzar ahora; ve el 75% como un posible bloqueo hacia adelante."),
  ("Decurnex", "Por coherencia, 75%",
   "El Estatuto vigente dice 50 + 1, pero “si hace dos meses votamos algo, no puede ser que hoy, 60 días después, el proyecto que eventualmente va a ser el más importante de la historia de Nacional…”; lo va a plantear como moción en la Asamblea {F-0015 00:26:52} {F-0015 00:27:13}. El 30/09: es difícil que la reforma esté aprobada antes del 24, pero es “un tema de conciencia” {F-0022 00:21:13}, y cada etapa “tiene que pasar necesariamente por asamblea” {F-0022 00:20:12}.",
   "Un proyecto de 30 años aprobado por poco margen divide al club."),
  ("Singlet", "Nos pareció que era tomarnos el pelo",
   "La reforma del 7 de julio fijó el 75% para proyectos de más de USD 2 M. Dos o tres días después, Aldabalde dijo que esta Asamblea se regiría por el Estatuto vigente, con 51%: “a nosotros no nos gustó esa actitud” {F-0017 00:05:19} {F-0017 00:07:23}. Un proyecto de esta envergadura aprobado con 51% “es porque no conoce el club” {F-0017 00:09:40}.",
   "Participó en la redacción de la reforma."),
 ],
 analisis=[
  "**Legalmente, parece mandar el Estatuto vigente, y es lo que sostiene Gomensoro, que es abogado y fue miembro informante de la reforma** {F-0021 00:59:59}. Si la reforma no está aprobada por el MEC, en principio no rige. Pero Gomensoro es parte, y no tenemos el Estatuto ni el trámite. La moción se remite a los Estatutos “sin perjuicio de cualquier exigencia estatutaria más rigurosa que resulte vigente” {F-0026 p.1}: si la reforma entrara en vigor antes, esa cláusula parece dejarla aplicar. Esto no es una opinión jurídica. [[CG]]",
  "**Políticamente, Decurnex y Singlet tienen un punto.** Un proyecto de 30 años aprobado 52 a 48 nace débil: cada Directiva futura va a tener la tentación de revisarlo. Aldabalde lo sabe: dice que si se aprueba por poco o no se aprueba, “no pasa nada”, pero también que se necesita el apoyo del socio.",
  "**La versión 2 cambia los términos de esta discusión.** La v1 pedía el voto unánime de los once directivos {F-0007 p.8}; la v2 lo saca y agrega una segunda Asamblea que decide el alcance definitivo con ejecutivos, contratos y financiamiento {F-0026 p.5}. Parte de lo que se buscaba con el 75%, que los socios no aprueben a ciegas, queda cubierto por esa segunda votación. Lo que no cambia es la mayoría: ni el 24 de octubre ni en la segunda Asamblea la moción fija una mayoría especial.",
  "**Lo que se vota es menos de lo que suena.** Según la moción, no se autorizan obras, deuda ni garantías, y los socios vuelven a votar el alcance definitivo {F-0026 p.5}. Se fija un rumbo, este Master Plan como marco {F-0026 p.2}, pero la v2 dice que las unidades se pueden “adaptar, postergar o excluir” {F-0026 p.2}. Con la v1, el solo estadio parecía un cambio de “esencia” que volvía a la Asamblea {F-0007 p.9}; con la v2, es una de las opciones que se estudian {F-0026 p.3}.",
  "**Puede que haya una sola moción.** Se informó que la v2 se votó en la Directiva 11 a 11 y que la agrupación Atilio García está conforme; todavía no registramos una fuente. Si la alternativa igual se presentara {F-0023}, según Gomensoro se votan en orden y, si sale la primera, la otra no se vota {F-0021 00:15:13}. Ver el apartado de la [[>../#otra-mocion|otra moción]] en la portada.",
 ],
 lectura="El 24 de octubre no se vota “hacer o no hacer la obra”, pero sí cuál es el proyecto de referencia. Por eso la mayoría importa. Una salida razonable sería que la propia Asamblea decida primero, como moción de orden, qué mayoría va a exigirse. Así la discusión de la regla no contamina la discusión del proyecto.",
 resolveria=["Texto de la reforma del Estatuto, umbral exacto y estado del trámite en el MEC", "Opinión jurídica independiente sobre si la Asamblea puede autoimponerse una mayoría especial", "Orden de votación si se presentan las dos mociones"],
),
}
